const deck = [
  { suit: "2H", value: 2 },
  { suit: "3H", value: 3 },
  { suit: "4H", value: 4 },
  { suit: "5H", value: 5 },
  { suit: "6H", value: 6 },
  { suit: "7H", value: 7 },
  { suit: "8H", value: 8 },
  { suit: "9H", value: 9 },
  { suit: "TH", value: 10 },
  { suit: "JH", value: 10 },
  { suit: "QH", value: 10 },
  { suit: "KH", value: 10 },
  { suit: "AH", value: 11 },

  { suit: "2D", value: 2 },
  { suit: "3D", value: 3 },
  { suit: "4D", value: 4 },
  { suit: "5D", value: 5 },
  { suit: "6D", value: 6 },
  { suit: "7D", value: 7 },
  { suit: "8D", value: 8 },
  { suit: "9D", value: 9 },
  { suit: "TD", value: 10 },
  { suit: "JD", value: 10 },
  { suit: "QD", value: 10 },
  { suit: "KD", value: 10 },
  { suit: "AD", value: 11 },

  { suit: "2C", value: 2 },
  { suit: "3C", value: 3 },
  { suit: "4C", value: 4 },
  { suit: "5C", value: 5 },
  { suit: "6C", value: 6 },
  { suit: "7C", value: 7 },
  { suit: "8C", value: 8 },
  { suit: "9C", value: 9 },
  { suit: "TC", value: 10 },
  { suit: "JC", value: 10 },
  { suit: "QC", value: 10 },
  { suit: "KC", value: 10 },
  { suit: "AC", value: 11 },

  { suit: "2S", value: 2 },
  { suit: "3S", value: 3 },
  { suit: "4S", value: 4 },
  { suit: "5S", value: 5 },
  { suit: "6S", value: 6 },
  { suit: "7S", value: 7 },
  { suit: "8S", value: 8 },
  { suit: "9S", value: 9 },
  { suit: "TS", value: 10 },
  { suit: "JS", value: 10 },
  { suit: "QS", value: 10 },
  { suit: "KS", value: 10 },
  { suit: "AS", value: 11 },

  // copy
  { suit: "2H", value: 11 },
  { suit: "3H", value: 11 },
  { suit: "4H", value: 11 },
  { suit: "5H", value: 11 },
  { suit: "6H", value: 11 },
  { suit: "7H", value: 11 },
  { suit: "8H", value: 11 },
  { suit: "9H", value: 11 },
  { suit: "TH", value: 11 },
  { suit: "JH", value: 11 },
  { suit: "QH", value: 11 },
  { suit: "KH", value: 11 },
  { suit: "AH", value: 11 },

  { suit: "2D", value: 11 },
  { suit: "3D", value: 11 },
  { suit: "4D", value: 11 },
  { suit: "5D", value: 11 },
  { suit: "6D", value: 11 },
  { suit: "7D", value: 11 },
  { suit: "8D", value: 11 },
  { suit: "9D", value: 11 },
  { suit: "TD", value: 11 },
  { suit: "JD", value: 11 },
  { suit: "QD", value: 11 },
  { suit: "KD", value: 11 },
  { suit: "AD", value: 11 },

  { suit: "2C", value: 11 },
  { suit: "3C", value: 11 },
  { suit: "4C", value: 11 },
  { suit: "5C", value: 11 },
  { suit: "6C", value: 11 },
  { suit: "7C", value: 11 },
  { suit: "8C", value: 11 },
  { suit: "9C", value: 11 },
  { suit: "TC", value: 11 },
  { suit: "JC", value: 11 },
  { suit: "QC", value: 11 },
  { suit: "KC", value: 11 },
  { suit: "AC", value: 11 },

  { suit: "2S", value: 11 },
  { suit: "3S", value: 11 },
  { suit: "4S", value: 11 },
  { suit: "5S", value: 11 },
  { suit: "6S", value: 11 },
  { suit: "7S", value: 11 },
  { suit: "8S", value: 11 },
  { suit: "9S", value: 11 },
  { suit: "TS", value: 11 },
  { suit: "JS", value: 11 },
  { suit: "QS", value: 11 },
  { suit: "KS", value: 11 },
  { suit: "AS", value: 11 },
];

const score = {
  playerScore: 0,
  dealerScore: 0,
};

export { deck, score };
